# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: 'windows-2019'



steps:
- task: JavaToolInstaller@0
  inputs:
    versionSpec: '11'
    jdkArchitectureOption: 'x64'
    jdkSourceOption: 'PreInstalled'

- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: python --version
  displayName: 'check python version'
  
- script:  java -version
  displayName: 'check java version'

- script:  python ts_scripts/install_dependencies.py --cuda=cu101 --environment=dev
  displayName: 'run install_dependencies'
  
 
- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
