# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: 'windows-2019'


steps:

- task: JavaToolInstaller@0
  inputs:
    versionSpec: '11'
    jdkArchitectureOption: 'x64'
    jdkSourceOption: 'PreInstalled'

- script:  python ts_scripts/install_dependencies.py --cuda=cu101 --environment=dev
  displayName: 'run install_dependencies'

- script:  python ts_scripts/install_from_src.py 
  displayName: 'run install from source'
 
- script:  python torchserve_sanity.py
  displayName: 'run sanity suite'

- script:  python test/regression_tests.py
  displayName: 'run regression suite'

- task: CopyFiles@2
  inputs:
    contents: 'frontend/server/build/reports/**'
    targetFolder: $(Build.ArtifactStagingDirectory)
- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: $(Build.ArtifactStagingDirectory)
    artifactName: frontend_build_reports
  